# Generated by Django 4.2.16 on 2026-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number for admin to reach client if needed', max_length=20),
        ),
    ]
