# Generated by Django 4.2.16 on 2026-03-06 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final price shown to client (may include Forge Africa margin)', max_digits=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Message to client about this quote')),
                ('sent_to_client_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='rfqs.rfq')),
                ('selected_bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote', to='bids.bid')),
            ],
        ),
    ]
