# Generated by Django 4.2.16 on 2026-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='deposit_percentage',
            field=models.PositiveIntegerField(default=30, help_text='Deposit % required from client to start the project'),
        ),
        migrations.AddField(
            model_name='quote',
            name='forge_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Forge Africa margin % added on top of vendor bid', max_digits=5),
        ),
    ]
